language: elixir

otp_release:
  - 18.0
  - 19.0
  - 20.0

elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.0
  - 1.5.1

matrix:
  exclude:
  - otp_release: 19.0
    elixir: 1.1.1
  - otp_release: 20.0
    elixir: 1.1.1
  - otp_release: 20.0
    elixir: 1.2.6
  - otp_release: 18.0
    elixir: 1.5.1

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0152272011bece7f993c
    on_success: change
    on_failure: always
    on_start: false


after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
